module.exports = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  jsxSingleQuote: true,
  quoteProps: 'as-needed',
  semi: false,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  proseWrap: 'preserve',
  vueIndentScriptAndStyle: true,
  htmlWhitespaceSensitivity: 'css',
  requirePragma: false,
  insertPragma: false,
  endOfLine: 'auto',
}
