name: Master - Baseline
on:
  push:
    branches:
      - master
jobs:
  master_check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Cache yarn'
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Cache node_modules'
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Visual Regression Test (changed dir)'
        run: yarn test
        env:
          GITHUB_TARGET_BRANCH: ${{ github.base_ref }}
          GITHUB_REPO: ${{ github.repository }}
          PERCY_BRANCH: ${{ github.head_ref }}
          PERCY_STATIC_SITE: ${{ secrets.PERCY_STATIC_SITE }}
          PERCY_STORYBOOK_COMPONENTS: ${{ secrets.PERCY_STORYBOOK_COMPONENTS }}
