name: Master - Baseline
on:
  push:
    branches:
      - master
jobs:
  master_check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Cache yarn'
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Cache node_modules'
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile && yarn lerna bootstrap
      - name: 'Visual Regression Test'
        run: yarn test:ci
        env:
          HAPPO_COMMAND: "./node_modules/.bin/happo"
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
