name: Master - Baseline
on:
  push:
    branches:
      - master
jobs:
  re-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Cache yarn'
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Cache node_modules'
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Visual Regression Test (changed dir)'
        run: cd examples/storybook-components && yarn test:ci
        env:
          PREVIOUS_SHA: ${{ github.event.pull_request.base.sha }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha }}
          CHANGE_URL: ${{ github.event.pull_request.html_url }}
          HAPPO_COMMAND: '../../node_modules/happo.io/build/cli.js'
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
          INSTALL_CMD: 'lerna bootstrap'
